language: node_js
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'DROP DATABASE IF EXISTS epic_mail;' -U postgres
  - psql -c 'create database epic_mail;' -U postgres
env:
  - SECRETKEY='secretjwtkey'  
script:
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls


